name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.doumen-laumen.de/node-wine:latest
    - name: Publish the Docker image
      run: | 
       docker tag docker.doumen-laumen.de/node-wine:latest
       docker push docker.doumen-laumen.de/node-wine:latest
